== 상품 저장
=== 성공: request가 valid한 경우
operation::product-controller-unit-test/save-product_-when-valid-request_-should-return-product-id-location[snippets="http-request,http-response"]

=== 실패: request가 invalid한 경우
operation::product-controller-unit-test/save-product_-when-in-valid-request_-should-throw-exception[snippets="http-request,http-response"]

== 상품 수정
=== 성공: request가 valid한 경우
operation::product-controller-unit-test/update-product_-when-valid-request_-should-return-ok[snippets="http-request,http-response"]

=== 실패: request가 invalid한 경우
operation::product-controller-unit-test/update-product_-when-in-valid-request_-should-throw-exception[snippets="http-request,http-response"]

== 상품 삭제
=== 성공: request가 valid한 경우
operation::product-controller-unit-test/delete-product_-when-valid-request_-should-return-ok[snippets="http-request,http-response"]

=== 실패: request가 invalid한 경우
operation::product-controller-unit-test/delete-product_-when-in-valid-request_-should-throw-exception[snippets="http-request,http-response"]